# Makefile for the AW_Lib
#
# @author Marcelo Coraça de Freitas <marcelo.batera@gmail.com> 

ADA_PROJECT_PATH=.:../awlib

projectFile="awsec.gpr"


libs:
	ADA_PROJECT_PATH=${ADA_PROJECT_PATH} gnatmake -P ${projectFile}

all: libs


clean:
	@ADA_PROJECT_PATH=${ADA_PROJECT_PATH} gnatclean -P ${projectFile}
	@echo "All clean"

docs:
	@-./gendoc.sh
	@echo "The documentation is generated by a bash script. Then it might fail in other platforms"
